// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Login struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type User struct {
	UserID   string `json:"userID"`
	UserName string `json:"userName"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
